FlatFound/FlatFound/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('core.urls')),
    path('properties/', include('property.urls')),
    path('dashboard', include('dashboard.urls')),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FlatFound/core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('index/', views.index, name='index'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('about/', views.about, name='about'),
    path('infocontact/', views.infocontact, name='infocontact'),
    path('privacypolicy/', views.privacypolicy, name='privacypolicy'),
    path('terms/', views.terms, name='terms')
]

FlatFound/property/urls.py
from django.urls import path
from . import views

app_name = 'property'

urlpatterns = [
    path('', views.property, name='properties'),
    path('new/', views.new, name='new'),
    path('fav/<int:id>/', views.favourite_add, name='favourite_add' ),
    path('favourites/', views.favourite_list, name='favourite_list' ),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
]

FlatFound/property/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name  # Shows the name of property on admin page
    
class Countries(models.Model):
    name = models.CharField(max_length=255)
    
    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Countries'
        
    def __str__(self):
        return self.name


class Property(models.Model):
    country = models.ForeignKey(Countries, related_name='countries', on_delete=models.CASCADE)
    city = models.TextField(blank=True, null=True)
    category = models.ForeignKey(Category, related_name='properties', on_delete=models.CASCADE)
    price_PCM = models.IntegerField()
    PPW = models.FloatField()
    address = models.TextField(blank=True, null=True)
    postcode = models.TextField(blank=True, null=True)
    pet_friendly = models.BooleanField(blank=True, null=True)
    number_of_beds = models.IntegerField(blank=True, null=True)
    number_of_bathrooms = models.IntegerField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    image1 = models.ImageField(upload_to='prop_images', blank=True, null=True)
    image2 = models.ImageField(upload_to='prop_images', blank=True, null=True)
    image3 = models.ImageField(upload_to='prop_images', blank=True, null=True)
    image4 = models.ImageField(upload_to='prop_images', blank=True, null=True)
    favourites = models.ManyToManyField(User, related_name='favourite', default=None, blank=True)
    # If the user is deleted then so are their properties.
    created_by = models.ForeignKey(
        User, related_name='properties', on_delete=models.CASCADE)
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.address

FlatFound/property/forms.py
from django import forms

from .models import Property

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'


class NewListingForm(forms.ModelForm):
    class Meta:
        model = Property
        fields = ('country', 'city', 'category',  'price_PCM', 'PPW', 'address', 'postcode',
                  'pet_friendly', 'number_of_beds', 'number_of_bathrooms', 'description', 'image1', 'image2', 'image3', 'image4',)
        widgets = {
            'country': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'city': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'category': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'price_PCM': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'PPW': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'address': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'postcode': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'pet_friendly': forms.CheckboxInput(attrs={
                'class': INPUT_CLASSES
            }),
            'number_of_beds': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'number_of_bathrooms': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'image1': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image2': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image3': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image4': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
        }


class EditListingForm(forms.ModelForm):
    class Meta:
        model = Property
        fields = ('country', 'city', 'category',  'price_PCM', 'PPW', 'address', 'postcode',
                  'pet_friendly', 'number_of_beds', 'number_of_bathrooms', 'description', 'image1', 'image2', 'image3', 'image4',)
        widgets = {
            'country': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'city': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'category': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'price_PCM': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'PPW': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'address': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'postcode': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'pet_friendly': forms.CheckboxInput(attrs={
                'class': INPUT_CLASSES
            }),
            'number_of_beds': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'number_of_bathrooms': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'image1': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image2': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image3': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image4': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
        }

FlatFound/property/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect

from .forms import NewListingForm, EditListingForm
from .models import Category, Property, Countries

# Create your views here.
from django.shortcuts import render
from django.db.models import Q
from .models import Property, Category, Countries

def property(request):
    query = request.GET.get('query', '')
    category_id = request.GET.get('category', 0)
    selected_country_id = request.GET.get('countries', '')
    
    # Retrieve all categories and countries for the filter options
    categories = Category.objects.all()
    countries = Countries.objects.all()
    
    # Retrieve all properties
    properties = Property.objects.all()
    
    # Apply filters based on user selections
    if category_id:
        properties = properties.filter(category_id=category_id)
    
    if selected_country_id:
        properties = properties.filter(country_id=selected_country_id)
    
    # Apply search query if provided
    if query:
        properties = properties.filter(
            Q(postcode__icontains=query) | Q(description__icontains=query))
    
    # Convert selected_country_id to integer with default value 0 if empty string
    selected_country_id = int(selected_country_id) if selected_country_id else 0
    
    return render(request, 'property/listings.html', {
        'properties': properties,
        'query': query,
        'categories': categories,
        'countries': countries,
        'selected_category_id': int(category_id),
        'selected_country_id': selected_country_id,
    })


def detail(request, pk):
    property = get_object_or_404(Property, pk=pk)
    related_properties = Property.objects.filter(
        category=property.category).exclude(pk=pk)[0:3]
    return render(request, 'property/detail.html', {
        'property': property,
        'related_properties': related_properties
    })


@login_required
def new(request):
    if request.method == 'POST':
        form = NewListingForm(request.POST, request.FILES)

        if form.is_valid():
            property = form.save(commit=False)
            property.created_by = request.user
            property.save()

            return redirect('property:detail', pk=property.id)
    else:
        form = NewListingForm()

    return render(request, 'property/form.html', {
        'form': form,
        'title': 'New Property',
    })


@login_required
def edit(request, pk):
    property = get_object_or_404(Property, pk=pk, created_by=request.user)

    if request.method == 'POST':
        form = EditListingForm(request.POST, request.FILES, instance=property)

        if form.is_valid():
            form.save()

            return redirect('property:detail', pk=property.id)
    else:
        form = EditListingForm(instance=property)

    return render(request, 'property/form.html', {
        'form': form,
        'title': 'Edit property',
    })


@login_required
def delete(request, pk):
    property = get_object_or_404(Property, pk=pk, created_by=request.user)
    property.delete()

    return redirect('dashboard:index')


@login_required
def favourite_add(request, id):
    property = get_object_or_404(Property, id=id)
    if property.favourites.filter(id=request.user.id).exists():
        property.favourites.remove(request.user)
    else:
        property.favourites.add(request.user)
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

@login_required
def favourite_list(request):
    new = Property.objects.filter(favourites=request.user)
    return render(request,'property/favourites.html', {'new': new})

FlatFound/property/templates/property/detail.html
{% extends 'core/base.html' %}
{% load static %} {# Ensure you have this at the top if you're using static files #}

{% block content %}

<div class="grid grid-cols-5 gap-6">
    <div class="col-span-2">
        <img src="{{ property.image1.url }}" class="rounded-xl mb-6" alt="">
        <img src="{{ property.image2.url }}" class="rounded-xl mb-6" alt="">
        <img src="{{ property.image3.url }}" class="rounded-xl mb-6" alt="">
        <img src="{{ property.image4.url }}" class="rounded-xl mb-6" alt="">
    </div>
    <div class="col-span-3 p-6 bg-gray-100 rounded-xl">
        <h1 class="text-3xl mb-4">Property Details</h1>
        <div class="bg-white rounded-xl p-4 mb-6">
            <h2 class="text-xl font-semibold mb-2">Description</h2>
            <p class="text-gray-700">{{ property.description }}</p>
        </div>
        <div class="grid grid-cols-2 gap-4 mb-6">
            <div class="bg-white rounded-xl p-4 flex items-center">
                <i class="fas fa-pound-sign text-lg text-gray-500 mr-2"></i>
                <div>
                    <p class="font-semibold">Price per week</p>
                    <p>£{{ property.PPW }}</p>
                </div>
            </div>
            <div class="bg-white rounded-xl p-4 flex items-center">
                <i class="fas fa-user text-lg text-gray-500 mr-2"></i>
                <div>
                    <p class="font-semibold">Pet Friendly</p>
                    {% if property.pet_friendly == True %}
                        <p>Yes</p>
                    {% else %}
                        <p>No</p>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="grid grid-cols-2 gap-4 mb-6">
            <div class="bg-white rounded-xl p-4 flex items-center">
                <i class="fas fa-map-marker-alt text-lg text-gray-500 mr-2"></i>
                <div>
                    <p class="font-semibold">Postcode</p>
                    <p>{{ property.postcode }}</p>
                </div>
            </div>
            <div class="bg-white rounded-xl p-4 flex items-center">
                <i class="fas fa-calendar-alt text-lg text-gray-500 mr-2"></i>
                <div>
                    <p class="font-semibold">Tenancy Length</p>
                    <p>{{ property.category.name }}</p>
                </div>
            </div>
        </div>
        <div class="grid grid-cols-2 gap-4 mb-6">
            <div class="bg-white rounded-xl p-4 flex items-center">
                <i class="fas fa-map-marker-alt text-lg text-gray-500 mr-2"></i>
                <div>
                    <p class="font-semibold">PCM</p>
                    <p>£{{ property.price_PCM }}</p>
                </div>
            </div>
            <div class="bg-white rounded-xl p-4 flex items-center">
                <i class="fas fa-calendar-alt text-lg text-gray-500 mr-2"></i>
                <div>
                    <p class="font-semibold">City</p>
                    <p>{{ property.city }}</p>
                </div>
            </div>
        </div>
        <div class="grid grid-cols-2 gap-4 mb-6">
            <div class="bg-white rounded-xl p-4 flex items-center">
                <i class="fas fa-map-marker-alt text-lg text-gray-500 mr-2"></i>
                <div>
                    <p class="font-semibold">Bathrooms</p>
                    <p>{{ property.number_of_bathrooms }}</p>
                </div>
            </div>
            <div class="bg-white rounded-xl p-4 flex items-center">
                <i class="fas fa-calendar-alt text-lg text-gray-500 mr-2"></i>
                <div>
                    <p class="font-semibold">Bedrooms</p>
                    <p>{{ property.number_of_beds }}</p>
                </div>
            </div>
        </div>
        {% if request.user == property.created_by %}
            <div class="bg-white mb-6 rounded-xl p-4 text-center">
                <div class="flex justify-around mt-4">
                    <a href="{% url 'property:edit' property.id %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl">EDIT</a>
                    <p>This is your property!</p>
                    <a href="{% url 'property:delete' property.id %}" class="px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl">DELETE</a>
                </div>
            </div>
        {% else %}
            <div class="text-center">
                <a href="mailto:{{ property.created_by.email }}" class="inline-block m-6 px-6 py-6 text-lg font-semibold bg-black text-white rounded-xl hover:bg-black">
                    Email Seller {{ property.created_by.email }}
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6 ml-2 inline-block align-middle">
                        <path d="M1.5 8.67v8.58a3 3 0 0 0 3 3h15a3 3 0 0 0 3-3V8.67l-8.928 5.493a3 3 0 0 1-3.144 0L1.5 8.67Z" />
                        <path d="M22.5 6.908V6.75a3 3 0 0 0-3-3h-15a3 3 0 0 0-3 3v.158l9.714 5.978a1.5 1.5 0 0 0 1.572 0L22.5 6.908Z" />
                    </svg>
                </a>
                <a href="{% url 'property:favourite_add' property.id %}" class="inline-flex items-center mt-4 px-6 py-6 text-lg font-semibold bg-black text-white rounded-xl hover:text-ccff66 hover:bg-black">
                    Add to favourites
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-6 h-6 inline-block align-middle ml-2">
                        <path d="m11.645 20.91-.007-.003-.022-.012a15.247 15.247 0 0 1-.383-.218 25.18247 25.18 0 0 1-4.244-3.17C4.688 15.36 2.25 12.174 2.25 8.25 2.25 5.322 4.714 3 7.688 3A5.5 5.5 0 0 1 12 5.052 5.5 5.5 0 0 1 16.313 3c2.973 0 5.437 2.322 5.437 5.25 0 3.925-2.438 7.111-4.739 9.256a25.175 25.175 0 0 1-4.244 3.17 15.247 15.247 0 0 1-.383.219l-.022.012-.007.004-.003.001a.752.752 0 0 1-.704 0l-.003-.001Z" />
                    </svg>
                </a>
            </div>
        {% endif %}
        <iframe src="https://maps.google.com/maps?q={{property.postcode}}&amp;t=&amp;z=13&amp;ie=UTF8&amp;iwloc=&amp;output=embed" width="100%" height="480" allowfullscreen=""></iframe>
    </div>
</div>

{% endblock %}

FlatFound/property/templates/property/favourites.html
{% extends 'core/base.html' %}

{% block title %} Dashboard {% endblock title %}

{% block content %}
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Your favourites</h2>
    <div class="grid grid-cols-3 gap-3">
        {% for property in new %}
        <div>
            <a href="{% url 'property:detail' property.id %}">
                <div class="">
                    <img src="{{ property.image1.url }}" alt="" class="rounded-t-xl">
                </div>
                <div class="p-6 bg-white rounded-b-xl">
                    <h2 class="text-2xl">PCM: £{{property.price_PCM}} </h2>
                    <h2 class="text-1xl">Tenancy Length: {{property.category}} </h2>
                    <p class="text-gray-500">Postcode: {{property.postcode}}, {{property.city}}</p>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

FlatFound/property/templates/property/form.html
{% extends 'core/base.html' %}

{% block title %} {{title}} {% endblock %}

{% block content %}
<h1 class="font-semibold m-20 text-3xl">{{ title }}</h1>
<form action="." method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="space-y-4 m-20 mb-0 mt-0 border-2 p-6 rounded-xl bg-gray-100 text-lg font-base">
        
        {{ form.as_p }}
    </div>

    {% if form.errors or form.non_field_errors %}
    <div class="mb-3 p-6 bg-red-100 rounded-xl">
        {% for field in form %}
            {% if field.errors %}
                {{ field.errors }}
            {% endif %}
        {% endfor %}
        
        {{ form.non_field_errors }}
    </div>
    {% endif %}

    <button class="mt-6 mx-20 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
</form>
{% endblock %}

FlatFound/property/templates/property/listings.html
{% extends 'core/base.html' %}
{% block title %} {{ property.price_pcm }} {% endblock %}

{% block content %}
<div class="pb-6 mx-auto w-11/12">
    <div class="grid grid-cols-4 gap-4 bg-gray-100 m-4">
        <div class="col-span-1 m-4">
            <p class="font-semibold">Duration of renting</p>
            <form action="{% url 'property:properties' %}" method="get">
                <input name="query" value="{{ query }}" type="text" class="m-4 w-full py-4 px-6 border rounded" placeholder="Enter a Country, City or Postcode">
                
                <select name="duration" class="m-4 w-full py-4 px-6 border rounded">
                    <option value="">Select Rental Period</option>
                    {% for category in categories %}
                    <option value="{{ category.id }}" {% if category.id == selected_category_id %} selected {% endif %}>{{ category.name }}</option>
                    {% endfor %}
                </select>
                <select name="countries" class="m-4 w-full py-4 px-6 border rounded">
                    <option value="">Select Country</option>
                    {% for country in countries %}
                        <option value="{{ country.id }}" {% if country.id == selected_country_id %} selected {% endif %}>{{ country.name }}</option>
                    {% endfor %}
                </select>
                
                <button class="mx-8 py-4 px-8 text-lg bg-teal-500 text-white rounded-xl">Search</button>
                <a href="{% url 'property:properties' %}" class="mt-2 py-4 px-8 inline-block bg-yellow-500 text-lg rounded-xl text-white">Remove Filters</a>
            </form>
        </div>
        <div class="col-span-2 m-2">
            {% for property in properties reversed %}
            {% if request.user != property.created_by %}
            <div>
                <a href="{% url 'property:detail' property.id %}" class="m-1">
                    <div>
                        <img src="{{ property.image1.url }}" alt="" class="rounded-t-xl">
                    </div>
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">PCM: £{{property.price_PCM}} </h2>
                        <h2 class="text-1xl">Tenancy Length: {{property.category}} </h2>
                        <p class="text-gray-500">Postcode: {{property.postcode}}, {{property.city}}</p>
                    </div>
                </a>
            </div>
            {% endif %}
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}