FlatFound/FlatFound/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('core.urls')),
    path('properties/', include('property.urls')),
    path('dashboard', include('dashboard.urls')),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FlatFound/core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('index/', views.index, name='index'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('about/', views.about, name='about'),
    path('infocontact/', views.infocontact, name='infocontact'),
    path('privacypolicy/', views.privacypolicy, name='privacypolicy'),
    path('terms/', views.terms, name='terms')
]

FlatFound/dashboard/urls.py
from django.urls import path
from . import views
app_name = 'dashboard'
urlpatterns = [
    path('', views.index, name='index'),
]

FlatFound/property/urls.py
from django.urls import path
from . import views

app_name = 'property'

urlpatterns = [
    path('', views.property, name='properties'),
    path('new/', views.new, name='new'),
    path('fav/<int:id>/', views.favourite_add, name='favourite_add' ),
    path('favourites/', views.favourite_list, name='favourite_list' ),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
]

FlatFound/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

def fdmgroup_email_validator(value):
    if not value.endswith("@fdmgroup.com"):
        raise ValidationError("Email must end with @fdmgroup.com")

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your Username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your Password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
        
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your Username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    email = forms.CharField(validators=[fdmgroup_email_validator], widget=forms.EmailInput(attrs={
        'placeholder': 'Your email @fdmgroup.com',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    

FlatFound/core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from property.models import Category, Property, Countries

from .forms import SignupForm

# Create your views here.

def index(request):
    properties = Property.objects.all()[0:6]
    categories = Category.objects.all
    countries = Countries.objects.all
    
    return render(request, 'core/index.html', {
        'countries': countries,
        'categories': categories,
        'properties': properties
    })

def contact(request):
    return render(request, 'core/contact.html')

def infocontact(request):
    return render(request, 'infocontact.html')

def about(request):
    return render(request, 'about.html')                  # these four are the views functions for new pages 

def privacypolicy(request):
    return render(request, 'privacypolicy.html')

def terms(request):
    return render(request, 'terms.html')

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        
        if form.is_valid():
            form.save()
            return redirect('/login/')
    else:
        form = SignupForm()
    
    return render(request, 'core/signup.html', {
        'form': form
    })
    

FlatFound/core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>{% block title %}{% endblock %} | FlatFound</title>
    <style>
        html, body {
            height: 100%;
            margin: 0;
            padding: 0;
            display: flex;
            flex-direction: column;
        }

        body {
            flex: 1;
        }

        footer {
            flex-shrink: 0;
            background-color: black;
        }

        .menu-option:hover, .title-option:hover, .footer-link {
            color: #ccff66;
        }

        .footer-title {
            color: white;
        }
    </style>
</head>
<body>
    <nav class="px-16 py-7 flex justify-between items-center border-b border-gray-200 bg-black text-white">
        {% if request.user.is_authenticated %}
        <a href="{% url 'core:index' %}" class="flex items-center space-x-2">
            <span class="text-xl font-semibold title-option">FlatFound</span>
        </a>
        <div class="space-x-6">
            {% csrf_token %}
            <a href="{% url 'property:properties' %}" class="text-lg font-semibold menu-option">Browse</a>
            <a href="{% url 'property:favourite_list' %}" class="text-lg font-semibold menu-option">Favourites</a>
            <a href="{% url 'dashboard:index' %}" class="text-lg font-semibold menu-option">Dashboard</a>
            <a href="{% url 'property:new' %}" class="text-lg font-semibold menu-option">New Listing</a>
            
        </div>
        {% else %}
        <a href="{% url 'core:login' %}" class="flex items-center space-x-2">
            <span class="text-xl font-semibold title-option">FlatFound</span>
        </a>
        <div class="space-x-6 ml-auto">
            <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700 hover:text-ccff66">Sign Up</a>
            <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700 hover:text-ccff66">Login</a>
        </div>
        {% endif %}
    </nav>
    
    <div class="px-6 py-6 flex-grow">{% block content %} {% endblock %}</div>
    
    <footer class="py-6 px-6 flex justify-between bg-black">
        <div class="m-2 w-2/3 pr-10">
            <h3 class="mb-5 font-semibold text-white footer-title">About</h3>
            <p class="text-lg text-gray-500">
                Search for property with the FDMgroup's property leading resource. Browse houses and flats for sale and to rent, and find estate agents in your area.
                View a property and gaining basic answers from a selling agent can provide you with a good amount of information regarding the property
            </p>
        </div>
        <div class="m-2 w-1/4">
            <h3 class="mb-5 font-semibold text-white footer-title">Menu</h3>
            <ul class="space-y-2">
                <li><a href="https://www.fdmgroup.com/about-us/" class="text-lg footer-link">About Us</a></li>
                <li><a href="https://www.fdmgroup.com/about-us/contact-us/" class="text-lg footer-link">Contact us</a></li>
                <li><a href="https://www.fdmgroup.com/privacy-policy/" class="text-lg footer-link">Privacy Policy</a></li>
                <li><a href="https://www.fdmgroup.com/terms-conditions/" class="text-lg footer-link">Terms of use</a></li>
                <li><form action="{% url 'core:logout' %}" method="post" class="text-lg footer-link">
                    {% csrf_token %}
                    <button type="submit">Logout</button>
                </form></li>
            </ul>
        </div>
    </footer>
</body>
</html>

FlatFound/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Welcome{% endblock title %}

{% block content %}


<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Newest Listings</h2>
    <img src="/FlatFound/media/prop_images/161101-obama-white-house-yellow-1105a.webp" alt="">
    <div class="grid grid-cols-3 gap-3">
        {% for property in properties reversed %}
        {% if request.user != property.created_by %}

        <div>
            <a href="{% url 'property:detail' property.id %}">
                <div class="">
                    <img src="{{ property.image1.url }}" alt="" class="rounded-t-xl">
                </div>
                <div class="p-6 bg-white rounded-b-xl">
                    <h2 class="text-2xl">PCM: £{{property.price_PCM}} </h2>
                    <h2 class="text-1xl">Tenancy Length: {{property.category}} </h2>
                    <p class="text-gray-500">Postcode: {{property.postcode}}, {{property.city}}</p>
                </div>
            </a>
        </div>
        {% endif %}
        {% endfor %}
    </div>
</div>


{% endblock %}

FlatFound/core/templates/core/login.html
{% extends 'core/base.html' %}
{% block title %}Sign up{% endblock %}
{% block content %}
<div class="w-1/2 my-6 mt-20 mb-40 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="p-3 flex items-center justify-center text-3xl">Login</h1>
    <form action="." method="post">
        {% csrf_token %}


        <div class="mb-3">
            <label for="" class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label for="" class="inline-block mb-2">Password</label><br>
            {{ form.password }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}
                
        {{ form.non_field_errors }}

            </div>
        {% endif %}

        <button class="py-4 px-8 mt-3 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white font-medium">Submit</button>
    </form>

    <div class="my-6 mx-auto p-6 bg-gray-100 rounded-xl">
        <h1 class="p-0 flex items-center justify-center text-xl">If you don't have an account already: &nbsp <a href="{% url 'core:signup' %}" class="py-3 px-3 bg-teal-500 font-medium hover:bg-teal-700 rounded-xl text-white">Sign up</a>
        </h1>
    </div>       
     <!-- <a href="{% url 'core:signup' %}" class="py-8 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Sign up</a> -->

</div>
{% endblock %}

FlatFound/core/templates/core/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>TEST</h1>
</body>
</html>

FlatFound/core/templates/core/signup.html
{% extends 'core/base.html' %}
{% block title %}Sign up{% endblock %}
{% block content %}
<div class="w-1/2 mt-20 mb-40 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="p-3 flex items-center justify-center text-3xl">Sign Up</h1>
    <form action="." method="post">
        {% csrf_token %}

        <div class="mb-3">
            <label for="" class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label for="" class="inline-block mb-2">Email</label><br>
            {{ form.email}}
        </div>

        <div class="mb-3">
            <label for="" class="inline-block mb-2">Password</label><br>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label for="" class="inline-block mb-2">Repeat Password</label><br>
            {{ form.password2}}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}
                
        {{ form.non_field_errors }}

            </div>
        {% endif %}

        <button class="py-4 px-8 mt-3 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}